### PR TITLE
Updated syntax

### PR DESCRIPTION
**Pull request by rakotomandimby**
Hi @simonrice , 

I would like to request you pull this patch that updates the syntax to the latest versions of Spark, Java and Tomcat.

Cheers

### CODE REVIEW

**Comment by rakotomandimby** [comment]
OK, my local build was with 1.8 and it is not recognized by Travis. I'll downgrade and submit.

**Comment by rakotomandimby** [comment]
The same code, compiled with java 1.7 gives

```
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[27,31] error: ')' expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[27,49] error: ')' expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[27,58] error: illegal start of expression
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[27,61] error: illegal start of expression
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[27,63] error: illegal start of expression
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[30,13] error: illegal start of type
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[32,17] error: <identifier> expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[32,18] error: illegal start of type
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,18] error: illegal start of type
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,19] error: ')' expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,26] error: ';' expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,34] error: illegal start of type
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,44] error: ';' expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,53] error: <identifier> expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,55] error: illegal start of type
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,56] error: <identifier> expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[33,57] error: ';' expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[34,22] error: illegal start of type
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[34,28] error: <identifier> expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[36,18] error: class, interface, or enum expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[37,8] error: class, interface, or enum expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[40,26] error: class, interface, or enum expected
[ERROR] /home/tomcat/project/SparkServletExample/src/main/java/com/simonrice/sparkservletexample/HelloWorld.java:[42,4] error: class, interface, or enum expected
```

I think the Travis build configuration should be updated to accept Java 8.
Thanks.

**Comment by SimonRice** [comment]
First of all, thank you very much for doing this.  As you may or may not be able to tell, I don't do much Java these days - I mostly work with Swift, Ruby and (to a lesser extent) Objective-C.

Feel free to change `.travis.yml`: you're using Java 8 syntax, which is substantially different from Java 6/7.  So don't worry about making sure it builds/works under Java 6/7.

The only other thing I would say is your closing of `Spark.get` is inconsistent between instances - one have your closing bracket and brace on the same line, the rest are on different lines.

Give these changes a go and we'll see how you get along.

**Comment by rakotomandimby** [comment]
@simonrice, you are welcome. As you probably noticed, I am not that good in Java either ;-)
I committed and pushed `travis.yml` update and some code cleaning.
Feel free to review :-)

**Comment by rakotomandimby** [comment]
@simonrice , it's OK now. I dont understand why Travis doesn't know `openjdk8`, but it's clean now. Regards.

**Comment by SimonRice** [comment]
Thank you very much for this - I'll have a proper look at things later today.

**Comment by rakotomandimby** [comment]
@simonrice , dont forget to merge it ;-)

**Comment by SimonRice** [comment]
Oops - thank you for reminding me!

**Pull request merged**
